#pragma config(Sensor, S1,     TouchSensor,    sensorTouch)
#pragma config(Sensor, S3,     LightSensor,    sensorLightActive)
#pragma config(Sensor, S4,     SonarSensor,    sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void GoUntilTouch() {
	motor[motorB] = 100;
	motor[motorC] = 100;
	while(SensorValue[TouchSensor] == 0) {
		wait1Msec(1);
	}
	motor[motorB] = -50;
	motor[motorC] = -50;
	wait1Msec(500);
}

void TurnLeft() {
	motor[motorB] = 40;
	motor[motorC] = -40;
	wait1Msec(800);
}

void TurnRight() {
	motor[motorB] = -40;
	motor[motorC] = 40;
	wait1Msec(800);
}

void Forward(int time) {
	motor[motorB] = 100;
	motor[motorC] = 100;
	wait1Msec(time);
}

void FollowTheBlackLineUntilSonarLessThan(int distance) {
	while(SensorValue[SonarSensor] == -1 || SensorValue[SonarSensor] > distance || SensorValue[SonarSensor] == 255) {
		if (SensorValue[LightSensor] > 45) {
			motor[motorB] = 40;
			motor[motorC] = 20;
		} else {
			motor[motorB] = 0;
			motor[motorC] = 80;
		}
	}
	motor[motorB] = 0;
	motor[motorC] = 0;
}

void ForwardRightUntilBlackLine() {
	while (SensorValue[LightSensor] > 45) {
		motor[motorB] = 15;
		motor[motorC] = 40;
	}
}

task main() {
	GoUntilTouch();
	TurnLeft();
	Forward(2500);
	FollowTheBlackLineUntilSonarLessThan(40);
	ForwardRightUntilBlackLine();
	Forward(300);
	ForwardRightUntilBlackLine();
	Forward(10000);
}
