#pragma config(Sensor, S1,     TouchSensor,    sensorTouch)
#pragma config(Sensor, S4,     SonarSensor,    sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void GoUntilWall(){
	motor[motorB] = 100;
	motor[motorC] = 100;
	while(SensorValue[SonarSensor] == -1 || SensorValue[SonarSensor] > 30 || SensorValue[SonarSensor] == 255) {
		wait1Msec(1);
	}
	//untilSonarLessThan(25, SonarSensor);
}

void TurnRight() {
	motor[motorB] = -40;//-10
	motor[motorC] = 40;//50
	wait1Msec(750);//500
}

task main() {
	GoUntilWall();
	TurnRight();
	GoUntilWall();
	TurnRight();
	GoUntilWall();
	TurnRight();
	GoUntilWall();
}
